### ISSUE TITLE
NQueens comparison

### ISSUE THREAD

**Issue by Martin1887** [willi-kappler/darwin-rs#15]
Hello.

In the README, you say that https://github.com/reem/rust-n-queens is faster than your example.

You can maybe also point to my genetic algorithm implementation, that solves the N Queens problem for N=255 in only few seconds 🙂: https://github.com/Martin1887/oxigen.

Regards.

**Comment by willi-kappler** [comment]
Nice crate, thanks for pointing it out!
I'll add a reference to it, your crate also seems to have a lot of more options ;-)
For darwin.rs I'll have to do a complete rewrite in the future, when I have more time...

**Comment by willi-kappler** [comment]
Reference to Oxigen added (e687ca8d3443302e7596dae1dbe5d4c511b61567)
